# Generated by Django 4.2 on 2023-05-13 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0022_alter_servicio_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bono',
            options={'verbose_name': 'Bono', 'verbose_name_plural': 'Bonos'},
        ),
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={'verbose_name': 'Estado de servicio', 'verbose_name_plural': 'Estados de servicio'},
        ),
        migrations.AlterModelOptions(
            name='grupobeneficiario',
            options={'verbose_name': 'Grupo de beneficiarios', 'verbose_name_plural': 'Grupos de beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='municipioservicio',
            options={'verbose_name': 'Municipio en servicio', 'verbose_name_plural': 'Municipios en servicio'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 12, 19, 37, 20, 997059)),
        ),
    ]
