# Generated by Django 4.2 on 2023-05-19 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0049_alter_servicio_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='jornada',
            field=models.CharField(choices=[('completa', 'Completa'), ('media_am', 'Media en la mañana'), ('media_pm', 'Media en la tarde'), ('todas', 'Todas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='municipioservicio',
            name='zona_ubicacion',
            field=models.CharField(choices=[('centro', 'Zona centro'), ('norte', 'Zona norte'), ('sur', 'Zona sur'), ('oriental', 'Zona oriental'), ('occidental', 'Zona occidental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 19, 14, 58, 25, 846816)),
        ),
    ]
