# Generated by Django 4.2 on 2023-05-20 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0050_alter_bono_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 20, 6, 18, 3, 406691)),
        ),
    ]
