# Generated by Django 4.2 on 2023-05-12 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0016_alter_colaborador_fecha_firma_contrato'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacionservicio',
            name='cliente_receptor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='persona.clientepersona'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 44, 0, 632981)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 44, 0, 632981)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 44, 0, 632981)),
        ),
    ]
