# Generated by Django 4.2 on 2023-05-13 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediopago',
            options={'verbose_name': 'Medio de pago', 'verbose_name_plural': 'Medios de pago'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 4, 51, 255187)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 4, 51, 255187)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 4, 51, 255187)),
        ),
    ]
