# Generated by Django 4.2 on 2023-05-13 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_mediopago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='prestacionservicio',
            options={'verbose_name': 'Prestación de servicio', 'verbose_name_plural': 'Prestaciones de servicio'},
        ),
        migrations.AlterModelOptions(
            name='tipoespacio',
            options={'verbose_name': 'Tipo de espacio', 'verbose_name_plural': 'Tipos de espacio'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 10, 22, 224089)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 10, 22, 224089)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 10, 22, 224089)),
        ),
    ]
