# Generated by Django 4.2 on 2023-05-15 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 20, 11, 201824)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 20, 11, 201824)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 20, 11, 201824)),
        ),
    ]
