# Generated by Django 4.2 on 2023-05-18 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_cotizacion', 'Pendiente de cotización'), ('cotizado', 'Cotizado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente_cotizacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 3, 32, 16, 713830)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 3, 32, 16, 713830)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 3, 32, 16, 713830), null=True),
        ),
    ]
