# Generated by Django 4.2 on 2023-06-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0042_alter_agenda_fecha_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 10, 57, 26, 443109)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 10, 57, 26, 443109)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 10, 57, 26, 443109), null=True),
        ),
    ]
