# Generated by Django 4.2 on 2023-07-02 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0058_alter_colaborador_fecha_firma_contrato'),
        ('pedido', '0043_alter_agenda_fecha_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='colaborador',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='colaborador', to='persona.colaborador'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 21, 53, 2, 756990)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 21, 53, 2, 756990)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 1, 21, 53, 2, 755859), null=True),
        ),
    ]
