# Generated by Django 4.2 on 2023-07-02 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0045_alter_agenda_fecha_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 21, 19, 2, 975394, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 16, 19, 2, 971271)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 2, 16, 19, 2, 971271), null=True),
        ),
    ]
