# Generated by Django 4.2 on 2023-07-04 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0047_alter_agenda_fecha_alter_factura_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 0, 39, 34, 584608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 19, 39, 34, 584608)),
        ),
        migrations.AlterField(
            model_name='prestacionservicio',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 3, 19, 39, 34, 584608), null=True),
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='jornada',
        ),
    ]
