# Generated by Django 4.1.5 on 2023-04-28 20:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CajaCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FondoCesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FondoPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('detalles_direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicio.grupobeneficiario')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicio.municipioservicio')),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='persona.tipoidentificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma_contrato', models.DateTimeField(default=datetime.datetime(2023, 4, 28, 15, 48, 14, 231456))),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='colaboradoras/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('categoria', models.CharField(choices=[('asignable', 'Asignable'), ('fijo', 'Fijo')], default='asignable', max_length=30)),
                ('autoriza_imagen_publica', models.BooleanField()),
                ('autorizacion_imagen_publica', models.FileField(blank=True, null=True, upload_to='colaboradoras/autorizaciones_imagen_publica/')),
                ('agenda', models.FileField(blank=True, null=True, upload_to='colaboradoras/agendas/')),
                ('arl', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.arl')),
                ('caja_compensacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.cajacompensacion')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.eps')),
                ('fondo_cesantias', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.fondocesantias')),
                ('fondo_pension', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.fondopension')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.rolpersona')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad')),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.clientepersona')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.rolpersona')),
            ],
        ),
    ]
