# Generated by Django 4.2 on 2023-05-13 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='arl',
            options={'verbose_name': 'ARL', 'verbose_name_plural': 'ARL'},
        ),
        migrations.AlterModelOptions(
            name='cajacompensacion',
            options={'verbose_name': 'Caja de compensación', 'verbose_name_plural': 'Cajas de compensación'},
        ),
        migrations.AlterModelOptions(
            name='clienteempresa',
            options={'verbose_name': 'Cliente Empresa', 'verbose_name_plural': 'Clientes Empresa'},
        ),
        migrations.AlterModelOptions(
            name='clientepersona',
            options={'verbose_name': 'Cliente Persona', 'verbose_name_plural': 'Clientes Persona'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'verbose_name': 'EPS', 'verbose_name_plural': 'EPS'},
        ),
        migrations.AlterModelOptions(
            name='fondocesantias',
            options={'verbose_name': 'Fondo de cesantías', 'verbose_name_plural': 'Fondos de cesantías'},
        ),
        migrations.AlterModelOptions(
            name='fondopension',
            options={'verbose_name': 'Fondo de pensión', 'verbose_name_plural': 'Fondos de pensión'},
        ),
        migrations.AlterModelOptions(
            name='identidad',
            options={'verbose_name': 'Identidad', 'verbose_name_plural': 'Identidades'},
        ),
        migrations.AlterModelOptions(
            name='rolpersona',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipoidentificacion',
            options={'verbose_name': 'Tipo de identificación', 'verbose_name_plural': 'Tipos de identificación'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 21, 10, 49, 519998)),
        ),
    ]
