# Generated by Django 4.2 on 2023-05-15 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0030_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteempresa',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad', unique=True),
        ),
        migrations.AlterField(
            model_name='clientepersona',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persona.identidad', unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 20, 11, 201824)),
        ),
    ]
