# Generated by Django 4.2 on 2023-05-18 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0038_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 4, 48, 14, 307995)),
        ),
    ]
