# Generated by Django 4.2 on 2023-05-19 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0046_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('incapacitado', 'Incapacitado'), ('en_vacaciones', 'En vacaciones'), ('limitado', 'Limitado'), ('inactivo', 'Inactivo')], default='activo', max_length=30),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 8, 41, 54, 878094)),
        ),
    ]
