# Generated by Django 4.2 on 2023-05-20 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0051_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientepersona',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 7, 53, 12, 974777)),
        ),
    ]
