# Generated by Django 4.2 on 2023-05-26 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0052_alter_clientepersona_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 15, 4, 42, 271350)),
        ),
    ]
