# Generated by Django 4.2 on 2023-07-02 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0057_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 21, 53, 2, 747318)),
        ),
    ]
