# Generated by Django 4.2 on 2023-07-08 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0062_alter_colaborador_fecha_firma_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='agenda',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 16, 2, 34, 944815)),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='colaboradoras/fotografias/'),
        ),
    ]
