# Generated by Django 4.1.7 on 2023-07-13 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0067_alter_colaborador_autorizacion_imagen_publica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_firma_contrato',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 21, 35, 20, 367287)),
        ),
    ]
