# Generated by Django 4.2 on 2023-05-05 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_colaborador_fecha_firma_contrato'),
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocontacto',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='registrocontacto',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='registrocontacto',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='registrocontacto',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='registrocontacto',
            name='usuario_responsable_respuesta',
        ),
        migrations.AddField(
            model_name='registrocontacto',
            name='remitente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='persona.identidad'),
        ),
        migrations.AddField(
            model_name='registrocontacto',
            name='responsable_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='persona.identidad'),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_radicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 3, 1, 6, 134663)),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 3, 1, 6, 134663)),
        ),
    ]
