# Generated by Django 4.2 on 2023-05-05 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_colaborador_fecha_firma_contrato'),
        ('contacto', '0002_remove_registrocontacto_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_radicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 3, 10, 13, 495925)),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 3, 10, 13, 495925)),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='persona.identidad'),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='responsable_respuesta',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='persona.identidad'),
        ),
    ]
