# Generated by Django 4.2 on 2023-05-13 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0021_alter_registrocontacto_fecha_radicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoregistrocontacto',
            options={'verbose_name': 'Estado de registros de contacto', 'verbose_name_plural': 'Estados de registros de contacto'},
        ),
        migrations.AlterModelOptions(
            name='registrocontacto',
            options={'verbose_name': 'Registro de contacto', 'verbose_name_plural': 'Registros de contacto'},
        ),
        migrations.AlterModelOptions(
            name='tipomensaje',
            options={'verbose_name': 'Tipo de mensaje', 'verbose_name_plural': 'Tipos de mensaje'},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'verbose_name': 'Tipo de usuario', 'verbose_name_plural': 'Tipos de usuario'},
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_radicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 19, 26, 44, 808818)),
        ),
        migrations.AlterField(
            model_name='registrocontacto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 19, 26, 44, 808818)),
        ),
    ]
